#!/usr/bin/env bash

if [ "$1" == "man" ]; then
    echo "
        arg 1 = Pull request title
        arg 2 = jira story number
        arg 3 = Local and testing environment test steps
        arg 4 = What kind of change does this PR introduce? (bugfix, feature, docs, update, custom message)
        arg 5 = What is the current behavior?
        arg 6 = What is the new behavior (if this is a feature change)?
        arg 7 = Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?) OPTIONAL
    "
    exit 0
else
    input_array=(
        "Pull request title"
        "What JIRA issue(s)/Zendesk does this address?"
        "Local and testing environment test steps"
        "What kind of change does this PR introduce? (bugfix, feature, docs update, ...)"
        "What is the current behavior?"
        "What is the new behavior"
        "Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)"
    )

    for i in {0..6} 
    do
        read -p "${input_array[$i]} : " input$i
    done

    change=""
    brchange="No"

    if [ "$input3" == "bugfix" ]; then
        change="Bugfix"
    elif [ "$input3" == "feature" ]; then
        change="Feature"
    elif [ "$input3" == "docs" ]; then
        change="Docs"
    elif [ "$input3" == "update" ]; then
        change="Update"
    fi

    if [ "$input6" != "" ]; then
        brchange="$input6"
    fi

    if [ ${#input1} > 4 ]; then
        url=(TIKET "$input1")[https://dsltd.zendesk.com/agent/tickets/"$input1"]
    else
        url=(DRAG-"$input1")[https://dandsltd.atlassian.net/browse/DRAG-"$input1"]
    fi

body=$(cat << EOF
    * **Please check if the PR fulfills these requirements**
    - [ ] The commit message follows our guidelines
    - [ ] Tests for the changes have been added (for bug fixes / features)
    - [ ] Docs have been added / updated (for bug fixes / features)

    * **What JIRA issue(s)/Zendesk ticket does this address?**
    $url

    * **Local and testing environment test steps**:
    "$input2"

    * **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
    "$change"    

    * **What is the current behavior?** (You can also link to an open issue here)
    "$input4"

    * **What is the new behavior (if this is a feature change)?**
    "$input5"

    * **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
    "$brchange"

    * **Other information**:
EOF
)

    gh pr create -B dev --title "$input0" --body $body
fi